export interface TemplatePrompt {
  id: number
  name: string
  namebn: string
  description: string
  descriptionbn: string
  categories: string[]
  aspectRatio: string
  prompt: string
}

export const TEMPLATE_CATEGORIES = [
  'All',
  'Social Proof',
  'Offer',
  'Comparison',
  'Testimonial',
  'UGC',
  'Editorial',
  'Product Hero',
  'Stats',
  'Before & After',
] as const

export type TemplateCategory = (typeof TEMPLATE_CATEGORIES)[number]

export const TEMPLATE_PROMPTS: TemplatePrompt[] = [
  {
    id: 1,
    name: "Headline",
    namebn: "হেডলাইন",
    description: "Tests text rendering. If this comes back clean, the model handles copy.",
    descriptionbn: "টেক্সট রেন্ডারিং টেস্ট। ক্লিন আসলে মডেল কপি হ্যান্ডেল করতে পারে।",
    categories: ["Product Hero"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Match the exact product colors, typography style, and brand tone precisely. Create: a static ad with a [BACKGROUND] background. Top third: large bold sans-serif headline reading "[YOUR HEADLINE, under 10 words]". Below in smaller text: "[YOUR SUBHEAD, one sentence]". Bottom half: [YOUR PRODUCT] on the surface with [DETAILS]. Shot at 50mm f/2.8 from slightly above. [BRAND] logo bottom right. Clean, authoritative. 4:5 aspect ratio.`,
  },
  {
    id: 2,
    name: "Offer/Promotion",
    namebn: "অফার / প্রোমোশন",
    description: "The money-maker. Test your core offer.",
    descriptionbn: "মূল অফার টেস্ট করার জন্য সেরা ফরম্যাট।",
    categories: ["Offer"],
    aspectRatio: "9:16",
    prompt: `Use the attached images as brand reference. Match exact brand colors and typography style. Create: a promotional ad with a split background. Top 60% is [PRIMARY BRAND COLOR] and bottom 40% is [CONTRAST COLOR like warm cream]. [YOUR PRODUCT] sits centered where colors meet, soft studio lighting. Upper area: large [CONTRAST TEXT] sans-serif reading "[YOUR OFFER like YOUR FIRST MONTH FREE]". Below: "[OFFER DETAILS]". Lower section: small [BRAND COLOR] text with [VALUE ADDS]. [BRAND] logo bottom right. 9:16 aspect ratio.`,
  },
  {
    id: 3,
    name: "Testimonials",
    namebn: "টেস্টিমোনিয়াল",
    description: "Real environments + text overlays. Tests composition depth.",
    descriptionbn: "বাস্তব পরিবেশ + টেক্সট ওভারলে। কম্পোজিশন ডেপথ টেস্ট করে।",
    categories: ["Testimonial", "Social Proof"],
    aspectRatio: "9:16",
    prompt: `Use the attached images as brand reference. Create: a testimonial ad set in [SETTING like bright bathroom / kitchen] with warm natural light. [YOUR PRODUCT] on [SURFACE], slightly out of focus. Overlaid: large bold white sans-serif "[SHORT HEADLINE]". Below: "[FULL QUOTE 2-3 sentences]. [NAME], [CREDENTIAL]." Five filled [BRAND COLOR] stars. [BRAND] logo bottom right in white. Shot on 35mm f/2.0. 9:16 aspect ratio.`,
  },
  {
    id: 4,
    name: "Features/Benefits Point-Out",
    namebn: "ফিচার / বেনিফিট পয়েন্ট-আউট",
    description: "Educational diagram-style layout.",
    descriptionbn: "এডুকেশনাল ডায়াগ্রাম স্টাইল লেআউট।",
    categories: ["Product Hero"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Create: an educational diagram-style ad on white background. Top: bold [BRAND COLOR] text "[HEADER like What Makes [PRODUCT] Different]". Below: [YOUR PRODUCT] centered, even studio lighting. Four callout boxes with connecting lines: "[BENEFIT 1-4]". Each has a small [BRAND COLOR] circle. "[WEBSITE]" bottom center. [BRAND] logo bottom right. Scientific diagram redesigned by a luxury agency. 4:5 aspect ratio.`,
  },
  {
    id: 5,
    name: "Bullet-Points",
    namebn: "বুলেট পয়েন্ট",
    description: "Split composition. Product left, benefits right.",
    descriptionbn: "স্প্লিট কম্পোজিশন। প্রোডাক্ট বাম, বেনিফিট ডান।",
    categories: ["Product Hero"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Create: a benefit-list ad, split composition on [BACKGROUND] background. Left 40%: [YOUR PRODUCT] on [SURFACE], shot at 85mm f/2.8. Right 60%: vertical stack of five lines with filled [BRAND COLOR] circles: "[BENEFIT 1-5]". Clean sans-serif, generous spacing. [BRAND] logo bottom right. 4:5 aspect ratio.`,
  },
  {
    id: 6,
    name: "Social Proof",
    namebn: "সোশ্যাল প্রুফ",
    description: "Member count + review card + press logos. The trust stack.",
    descriptionbn: "মেম্বার কাউন্ট + রিভিউ কার্ড + প্রেস লোগো। ট্রাস্ট স্ট্যাক।",
    categories: ["Social Proof"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Create: a social proof ad on [BACKGROUND like warm cream]. Top: "[HEADLINE like Join 1,000,000+ Members]" in bold [BRAND COLOR]. Five filled stars with "Rated [X] out of 5". Center: [YOUR PRODUCT] at 50mm f/4. Below: frosted white card with five-star rating, "[REVIEW TITLE]", "[2-3 SENTENCE REVIEW]", "[ATTRIBUTION]" in italic. Below card: "As Featured In" with five grayscale logos. [BRAND] logo bottom right. 4:5 aspect ratio.`,
  },
  {
    id: 7,
    name: "Us vs Them",
    namebn: "আমরা বনাম তারা",
    description: "Side-by-side comparison. Photography quality gap IS the argument.",
    descriptionbn: "পাশাপাশি তুলনা। ফটোগ্রাফি কোয়ালিটি পার্থক্যই আর্গুমেন্ট।",
    categories: ["Comparison"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Create: a side-by-side divided vertically. Left: muted gray-blue background. Right: [PRIMARY BRAND COLOR]. Center top: white circle with "VS". Left header: "[COMPETITOR CATEGORY]" + generic competitor product + list with X marks: "[WEAKNESS 1-5]". Right header: "[YOUR BRAND]" + [YOUR PRODUCT] + list with checkmarks: "[STRENGTH 1-5]". [BRAND] logo bottom right. 4:5 aspect ratio.`,
  },
  {
    id: 8,
    name: "Before & After (UGC Native)",
    namebn: "আগে ও পরে (UGC নেটিভ)",
    description: "Mirror selfie transformation. Must look like a real person posted it.",
    descriptionbn: "মিরর সেলফি ট্রান্সফর্মেশন। একদম অর্গানিক পোস্টের মতো দেখাতে হবে।",
    categories: ["Before & After", "UGC"],
    aspectRatio: "9:16",
    prompt: `Use the attached images as brand reference for product color ONLY. This should look like a real person's post. Create: TikTok before-and-after. LEFT: grainy iPhone mirror selfie, [PERSON] in dimly lit bathroom, [BEFORE STATE], harsh lighting. White handwritten text: "[BEFORE DATE]". RIGHT: same person, same bathroom, bright natural light, [AFTER STATE], [PRODUCT] visible on counter. White text: "[AFTER DATE]". Top center: "[TIMEFRAME] on [BRAND]" with emoji. Should look stitched in CapCut. 9:16 aspect ratio.`,
  },
  {
    id: 9,
    name: "Negative Marketing (Bait & Switch)",
    namebn: "নেগেটিভ মার্কেটিং (বেইট অ্যান্ড সুইচ)",
    description: "Fake bad review that's actually a rave. Scroll-stopper.",
    descriptionbn: "ফেক নেগেটিভ রিভিউ যা আসলে পজিটিভ। স্ক্রল-স্টপার।",
    categories: ["Testimonial", "Social Proof"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Create: Background is close-up of [PRODUCT], slightly blurred. Center: white rounded-rectangle review card (Amazon-style). Gray user icon, "[NAME]", one gold star + four gray, orange "Verified Purchase" badge, bold text: "[BAIT that sounds negative but is positive]". Bottom: bold white sans-serif "[PUNCHLINE like THE REVIEWS ARE IN.]". [BRAND] logo bottom right. 4:5 aspect ratio.`,
  },
  {
    id: 10,
    name: "Press/Editorial",
    namebn: "প্রেস / এডিটোরিয়াল",
    description: "Authority play. Vogue back-page energy.",
    descriptionbn: "অথরিটি প্লে। প্রিমিয়াম ম্যাগাজিন ভাইব।",
    categories: ["Editorial"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Create: a press ad on off-white linen background. Top: "As Featured In" in small [BRAND COLOR] uppercase wide-tracked text. Below: five grayscale publication logos. Center: italic serif pull-quote in [BRAND COLOR]: "[PRESS QUOTE]" with attribution. Lower third: [PRODUCT] at 85mm f/2.8, soft side light. [BRAND] logo bottom left. Generous white space. Full-page Vogue energy. 4:5 aspect ratio.`,
  },
  {
    id: 11,
    name: "Pull-Quote Review Card",
    namebn: "পুল-কোট রিভিউ কার্ড",
    description: "Emotional quote headline over a truncated review card on a color block. The \"...Read more\" creates an open loop.",
    descriptionbn: "ইমোশনাল কোট হেডলাইন + ট্রান্কেটেড রিভিউ কার্ড। '...আরও পড়ুন' ক্লিক বাড়ায়।",
    categories: ["Social Proof", "Testimonial"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Match the exact product colors and brand tone precisely. Create: a review-driven ad with a solid [BRAND COLOR with hex — a soft, muted tone works best] color block background filling the entire image. Top half: large bold italic serif text in white with curly quotation marks reading "[PULL-QUOTE — the most emotional 4-8 word phrase from the review, e.g., "I finally found something that works!"]". Directly below the quote: five large filled gold/yellow star icons in a horizontal row. Bottom left, overlapping the color background: a white rounded-corner review card with subtle shadow, containing: a small gray circular default avatar icon, beside it "[FIRST NAME + LAST INITIAL]" in bold dark sans-serif with a small [FLAG EMOJI matching target market — e.g., 🇺🇸], below the name a blue checkmark icon with "[VERIFIED REVIEWER / VERIFIED BUYER]" in small blue text. Below the reviewer info: the review body text in medium-weight dark sans-serif, 4-6 lines of authentic-sounding customer voice that trails off mid-sentence, ending with "...Read more" in bold [BRAND COLOR] text — the truncation is intentional to create curiosity. Below the review text: "Was this review helpful?" in small gray text with a thumbs-up icon and "[HELPFULNESS COUNT — e.g., 150 / 2.4K]" beside it. Bottom right, overlapping both the card and the color background: [YOUR PRODUCT — full packaging description] angled slightly toward the viewer, sitting on the color block surface with a subtle shadow beneath. No brand logo needed if the product packaging already shows it — the review card IS the social proof. 1:1 or 4:5 aspect ratio.`,
  },
  {
    id: 12,
    name: "Lifestyle Action + Product Colorway Array",
    namebn: "লাইফস্টাইল অ্যাকশন + প্রোডাক্ট কালার অ্যারে",
    description: "Action hero shot sells the use case. Fanned product lineup sells the range. Two conversion jobs in one frame.",
    descriptionbn: "অ্যাকশন শট ইউজ কেস বোঝায়। ফ্যান্ড প্রোডাক্ট লাইনআপ রেঞ্জ বোঝায়। এক ফ্রেমে দুটো কাজ।",
    categories: ["Product Hero"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design, colors, and visual tone precisely. Create: a static ad with a [LIFESTYLE PHOTO DESCRIPTION like man mid-golf-swing in tropical patterned polo and khaki pants] occupying the left two-thirds of the frame, shot outdoors in [SETTING like golf course with palm trees], bright natural daylight. [BRAND] logo top center in bold. Below logo: large bold sans-serif quote text reading "[ENDORSEMENT HEADLINE like THE GREATEST PANTS IN GOLF]" in [TEXT COLOR like white or black]. Bottom right foreground: three [PRODUCT VARIANTS like folded pairs of shorts/pants] fanned in an overlapping arrangement showing [COLOR 1], [COLOR 2], and [COLOR 3]. Products are crisp and studio-lit against the lifestyle background. Shot on 50mm f/2.0, lifestyle background slightly softer than foreground product. [MOOD like confident, athletic, aspirational but accessible]. 1:1 aspect ratio.`,
  },
  {
    id: 13,
    name: "Stat Surround / Callout Radial (Product Hero)",
    namebn: "স্ট্যাট সারাউন্ড / কলআউট রেডিয়াল (প্রোডাক্ট হিরো)",
    description: "Product is the sun. Stats are the planets. Arrows make it scannable in under 2 seconds.",
    descriptionbn: "প্রোডাক্ট কেন্দ্রে। স্ট্যাটস চারদিকে। ২ সেকেন্ডে স্ক্যানযোগ্য।",
    categories: ["Stats", "Product Hero"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design, colors, and typography style precisely. Create: a static ad on a white-to-[LIGHT GRADIENT COLOR like warm golden beige] gradient background, gradient fading from top to bottom. Top: large bold [TEXT COLOR like dark brown] sans-serif headline reading "[HEADLINE like So tasty you'll forget it's actually healthy.]" Center: [YOUR PRODUCT like single stand-up pouch] on white background, soft studio lighting. Floating near the product: a small circular badge reading "[PRICE POINT like AS LOW AS $2.63 PER MEAL!]" in [BADGE COLOR]. Flanking the product on both sides: four stat callouts with curved arrows pointing toward the product. Left side top: "[STAT 1 like 20g]" in oversized bold text with "[LABEL like PROTEIN]" below. Left side bottom: "[STAT 2 like 280]" with "[LABEL like CALORIES]". Right side top: "[STAT 3 like 900k+]" with "[LABEL like HAPPY CUSTOMERS]". Right side bottom: "[STAT 4 like 30k+]" with "[LABEL like 5-STAR REVIEWS]" and five filled gold stars beneath. Arrows are simple hand-drawn-style curved lines in [ARROW COLOR like black]. Bottom foreground: [FLAVOR PROPS like scattered chocolate chip cookie dough balls and chocolate chips] adding appetite appeal. No brand logo. Clean, informational, appetizing. 1:1 aspect ratio.`,
  },
  {
    id: 14,
    name: "Bundle Showcase + Benefit Bar",
    namebn: "বান্ডেল শোকেস + বেনিফিট বার",
    description: "Sells the system, not the SKU. The open box is the hero. The benefit bar handles the \"what's in it for me.\"",
    descriptionbn: "সিঙ্গেল প্রোডাক্ট না, পুরো সিস্টেম বিক্রি করে। ওপেন বক্সই হিরো।",
    categories: ["Product Hero", "Offer"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design, colors, and typography style precisely. Create: a static ad on a [BACKGROUND like soft pink-to-hot-pink gradient] background. Top: oversized bold white all-caps sans-serif headline reading "[HEADLINE like 24/7 PEAK FEMALE PERFORMANCE]". Below headline: a horizontal [ACCENT COLOR like purple/violet] banner bar divided into [NUMBER like five] equal segments separated by thin vertical lines, each containing a two-word benefit label in white text: "[BENEFIT 1 like Morning Energy]", "[BENEFIT 2 like Focus Amplifier]", "[BENEFIT 3 like Deep Sleep]", "[BENEFIT 4 like Ultimate Beauty]", "[BENEFIT 5 like Metabolism Booster]". Center-to-bottom: an open [PACKAGING like branded gift box] photographed at a slight overhead angle showing [NUMBER like three] [PRODUCTS like supplement jars] nestled inside, each a different [COLOR-CODED VARIANT]. In the lower foreground: a [LIFESTYLE PROP like woman's hand holding a pastel dumbbell] entering the frame from bottom. [BRAND] logo bottom left corner. Bright studio lighting, saturated color, energetic and empowering. 1:1 aspect ratio.`,
  },
  {
    id: 15,
    name: "Social Comment Screenshot + Product",
    namebn: "সোশ্যাল কমেন্ট স্ক্রিনশট + প্রোডাক্ট",
    description: "Screenshotted comment = instant credibility. Looks organic. Bold hook headline does the scroll-stopping.",
    descriptionbn: "স্ক্রিনশট করা কমেন্ট = তাৎক্ষণিক বিশ্বাসযোগ্যতা। অর্গানিক দেখায়।",
    categories: ["Social Proof", "UGC"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design and colors precisely. Create: a static ad on a clean white background. Top: oversized bold black sans-serif headline reading "[HOOK HEADLINE like IF YOU'RE GOING THROUGH PERI..]" with [EMOJI like 😅] at the end. Center: a social media comment card with light gray rounded-rectangle background containing: a small circular profile avatar (top left), bold name "[REVIEWER NAME like Elaine McLean]", and a multi-sentence review in regular-weight sans-serif: "[FULL REVIEW TEXT, 3-4 sentences, conversational and emotional]". Small gray timestamp "[TIMESTAMP like 2d]" below the comment. Bottom center: [YOUR PRODUCT like product box and bar/bottle] photographed at a slight angle on white, soft studio lighting. No brand logo. No stars. The rawness is the point — this should look like someone screenshotted a real comment and dropped the product photo below it. 1:1 aspect ratio.`,
  },
  {
    id: 16,
    name: "Curiosity Gap / Hook Quote Testimonial",
    namebn: "কিউরিওসিটি গ্যাপ / হুক কোট টেস্টিমোনিয়াল",
    description: "The bait-and-switch testimonial. Provocative headline forces the double-take. The reveal reframes it. Scroll-stop machine.",
    descriptionbn: "প্রোভোকেটিভ হেডলাইন ডাবল-টেক বাধ্য করে। রিভিল রিফ্রেম করে। স্ক্রল-স্টপ মেশিন।",
    categories: ["Testimonial"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design, colors, and typography style precisely. Create: a static ad on a clean white background. Top center: large [ACCENT COLOR like periwinkle blue] opening quotation marks. Below: mixed-weight headline in black — the first line in italic serif or semi-bold reading "[SETUP LINE like I've been]", the next two lines in enormous heavy-weight bold all-caps sans-serif reading "[BAIT PHRASE like FAKING IT / WITH MY HUSBAND]", followed by a smaller sentence-case line reading "[REVEAL like since perimenopause — with [BRAND] I don't have to]". Closing quotation marks and "[ATTRIBUTION like - Erin D.]" in regular weight. Left side bottom third: [YOUR PRODUCT like supplement bottle] at a slight angle with [PRODUCT DETAILS like capsules scattered nearby]. To the left of the product: a [TRUST BADGE like circular seal reading "Happiness 60 DAY Guaranteed"]. Right side bottom third: [NUMBER like five] filled [ACCENT COLOR] stars and bold text reading "[REVIEW COUNT like 3,600+] 5-Star Reviews" with a [BRAND ICON]. Bottom edge: small disclaimer text "[DISCLAIMER like Results may vary based on individual. No results guaranteed.]" 1:1 aspect ratio.`,
  },
  {
    id: 17,
    name: "Verified Review Card",
    namebn: "ভেরিফাইড রিভিউ কার্ড",
    description: "Mimics real review platform UI. The verified badge and helpfulness count do the trust-building work.",
    descriptionbn: "রিয়েল রিভিউ প্ল্যাটফর্ম UI মিমিক করে। ভেরিফাইড ব্যাজ বিশ্বাস তৈরি করে।",
    categories: ["Social Proof", "Testimonial"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design, colors, and typography style precisely. Create: a static ad on a solid [BRAND COLOR like periwinkle/lavender blue] background. Top: large bold white serif or semi-bold sans-serif pull-quote reading "[HEADLINE QUOTE like "I finally found something that works!"]" in quotation marks. Below the quote: five filled gold stars, large. Center-left: a white rounded-rectangle review card with subtle shadow containing: gray circular avatar icon, bold name "[REVIEWER NAME like Dawn K.]" with [FLAG EMOJI like 🇺🇸], blue checkmark and "[VERIFIED BADGE TEXT like Verified Reviewer]" in [BRAND COLOR] text, then 3-4 sentences of review body text in regular weight dark text. At the bottom of the card: a blue "[READ MORE like ...Read more]" link and "[HELPFULNESS like Was this review helpful? 👍 150]". Right side, overlapping the card edge: [YOUR PRODUCT like cream jar with lid] photographed at a slight angle, soft studio lighting, casting a gentle shadow on the background. No brand logo. The review UI is the trust mechanic. 1:1 aspect ratio.`,
  },
  {
    id: 18,
    name: "Stat Surround / Callout Radial (Lifestyle Flatlay)",
    namebn: "স্ট্যাট সারাউন্ড / কলআউট রেডিয়াল (লাইফস্টাইল ফ্ল্যাটলে)",
    description: "Same stat-radial format as #13, but lifestyle flatlay background and hand-held product sell the experience, not just the specs.",
    descriptionbn: "স্ট্যাট-রেডিয়াল ফরম্যাট, কিন্তু লাইফস্টাইল ফ্ল্যাটলে এক্সপেরিয়েন্স বিক্রি করে।",
    categories: ["Stats", "Product Hero"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design, colors, and typography style precisely. Create: a static ad on a white background with a lifestyle flatlay arrangement. Top: bold [ACCENT COLOR like purple] filled banner bar spanning full width, white all-caps sans-serif reading "[HEADLINE like INCREDIBLY TASTY BREAKFAST IN 30 SECONDS]". Center: a [PERSON DETAIL like woman's hand] holding [YOUR PRODUCT like branded shaker cup] in mid-frame. Scattered around the edges: [FLATLAY PROPS like product sachets, pancakes on plates, blueberries, muffins, fruit] arranged organically to fill corners and edges, slightly out of focus. Four stat callouts with curved [ACCENT COLOR] arrows pointing toward the held product: "[STAT 1 like 20g] / [LABEL like PROTEIN]", "[STAT 2 like 900K] / [LABEL like HAPPY CUSTOMERS]", "[STAT 3 like 20+] / [LABEL like FLAVORS]", "[STAT 4 like 30K] / [LABEL like 5 STAR REVIEWS]" with five small gold stars. Stats in bold black, labels in all-caps regular weight. Bright, flat studio lighting. Energetic, appetizing, information-dense but scannable. 1:1 aspect ratio.`,
  },
  {
    id: 19,
    name: "Highlighted / Annotated Testimonial",
    namebn: "হাইলাইটেড / অ্যানোটেটেড টেস্টিমোনিয়াল",
    description: "The highlighter pen does the work. Long-form review text with key phrases visually emphasized. Directs the eye to the money lines.",
    descriptionbn: "হাইলাইটার পেন কাজ করে। মূল লাইনে চোখ নিয়ে যায়।",
    categories: ["Testimonial", "Social Proof"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design, colors, and typography style precisely. Create: a static ad on a clean white background. Top left: circular customer headshot photo of [PERSON DESCRIPTION like smiling woman, mid-60s, silver wavy hair, wearing blue top]. To the right of the photo: bold name "[REVIEWER NAME like Veronica B.]" with a [VERIFIED ICON like blue checkmark]. Below: a long-form customer quote in large regular-weight black sans-serif type spanning most of the frame: "[FULL QUOTE, 3-5 sentences]". Key phrases within the quote are highlighted with [HIGHLIGHT COLOR like bright lime green / neon yellow] rectangular background fills behind the text: "[HIGHLIGHTED PHRASE 1 like thyroid removed]", "[HIGHLIGHTED PHRASE 2 like This is the best product I have found.]" Bottom right: [YOUR PRODUCT like supplement jar] at a slight angle, partially cropped at the bottom edge. To the left of the product: a circular [TRUST BADGE like "100% MONEY BACK / 90 DAYS / 100% GUARANTEE"] seal in [BADGE COLOR like lime green with dark text]. [BRAND] logo bottom left corner, small. 1:1 aspect ratio.`,
  },
  {
    id: 20,
    name: "Advertorial / Editorial Content Card",
    namebn: "অ্যাডভার্টোরিয়াল / এডিটোরিয়াল কন্টেন্ট কার্ড",
    description: "Looks like a news post, not an ad. The editorial framing creates curiosity and authority. Designed to blend into feed.",
    descriptionbn: "নিউজ পোস্টের মতো দেখায়, অ্যাড না। ফিডে মিশে যায়।",
    categories: ["Editorial", "UGC"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference for tone ONLY. Do NOT use polished ad layouts. This should look like organic editorial content. Create: a full-bleed moody portrait photo of [PERSON DESCRIPTION like young man in dark textured sweater holding an electric guitar], warm amber-toned lighting, shot on 50mm f/1.8, shallow depth of field, cinematic color grade with warm highlights and cool shadows. Lower 45% of the frame is a text overlay zone: a prominent white rounded-rectangle pill label reading "[CATEGORY TAG like HOT TOPIC]" in centered uppercase sans-serif, sized to span roughly one-third of the frame width. Below: very large, dominant, bold all-caps condensed sans-serif headline filling the width of the frame in white text with key words in [HIGHLIGHT COLOR]: "[HEADLINE like [BRAND] IS BLOWING UP ON TIKTOK — HERE'S WHY EVERYONE'S USING IT TO [ACTION]]". The headline should be oversized — at least 35% of the total frame height. Bottom center: "[@HANDLE like @waveform.watch]" in small white text. No product shot, no CTA button, no stars. This should read like a music blog or culture account post, not a paid ad. 4:5 aspect ratio.`,
  },
  {
    id: 21,
    name: "Bold Statement / Reaction Headline",
    namebn: "বোল্ড স্টেটমেন্ট / রিঅ্যাকশন হেডলাইন",
    description: "Pure brand energy. No stats. No reviews. Just a provocative line, a hot gradient, and the product. The copy IS the ad.",
    descriptionbn: "শুধু ব্র্যান্ড এনার্জি। স্ট্যাট নেই, রিভিউ নেই। কপিটাই অ্যাড।",
    categories: ["Product Hero"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design, colors, and visual tone precisely. Create: a static ad on a vibrant [GRADIENT like coral-pink to golden-yellow] gradient background, flowing diagonally from upper left to lower right. Upper left: oversized playful [FONT STYLE like rounded retro serif / Cooper Black style] white headline reading "[BOLD STATEMENT like This popcorn is so f*****g delicious.]" — text should feel loose, fun, and expressive, not rigid or corporate. Right side: [PERSON DETAIL like a hand reaching down from upper right] grabbing from [YOUR PRODUCT like the signature bright yellow popper bowl overflowing with fluffy popcorn]. Product sits center-right, slightly below midline. Bottom left: [BRAND] logo in [LOGO COLOR like black] with "[PRODUCT DESCRIPTOR like Flavor Wrapped Popcorn Kernels]" in smaller text below. No stats, no reviews, no badges. The gradient and the headline do all the work. 1:1 aspect ratio.`,
  },
  {
    id: 22,
    name: "Flavor Story / \"Tastes Like\"",
    namebn: "ফ্লেভার স্টোরি / \"এর মতো স্বাদ\"",
    description: "Food-visualization ad. The food IS the background.",
    descriptionbn: "ফুড ভিজ্যুয়ালাইজেশন অ্যাড। ফুডই ব্যাকগ্রাউন্ড।",
    categories: ["Product Hero"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design, colors, and packaging precisely. Create: a flavor-visualization ad. Full background is a photorealistic close-up food scene of [INDULGENT FOOD like freshly baked raspberry donuts dusted with powdered sugar on a gray stone surface]. Shot at 50mm f/2.8, shallow depth of field, warm bakery lighting. Top third: large bold white sans-serif headline reading "[HEADLINE like A protein bar that tastes like freshly baked raspberry donuts]" with one key word in bold italic for emphasis. [YOUR PRODUCT] packaged unit placed bottom-right, angled 15° as if casually laid into the scene. Bottom: semi-transparent white bar spanning full width with three stat columns separated by thin vertical lines: "[STAT 1 like 15g PROTEIN]" | "[STAT 2 like 2g SUGAR]" | "[STAT 3 like 180 CALORIES]". Very bottom edge: smaller bold sans-serif "[CLEAN LABEL CLAIM like NO ARTIFICIAL SWEETENERS]". Food is the hero — product is the payoff. 1:1 aspect ratio.`,
  },
  {
    id: 23,
    name: "Long-Form Manifesto / Letter Ad",
    namebn: "লং-ফর্ম ম্যানিফেস্টো / লেটার অ্যাড",
    description: "Copy-dominant. No imagery. The writing IS the ad.",
    descriptionbn: "কপি-ডমিন্যান্ট। ইমেজ নেই। লেখাটাই অ্যাড।",
    categories: ["Editorial"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match exact brand typography style and tone. Create: a copy-dominant manifesto ad on a clean white background. No background imagery — text is the entire creative. Top: oversized bold black serif or sans-serif headline reading "[PROVOCATIVE HEADLINE like They're not cheap.]" spanning the top 15%. Below: left-aligned body copy in smaller regular-weight black text, structured as short punchy sentences and line breaks (NOT paragraphs), building a persuasive argument about [CORE BRAND TENSION like why the price is justified]. The copy should flow through: acknowledging the objection, listing what you'd lose if they cut corners, reframing as a positive, closing with a confident brand statement. Approximately [12-18 LINES] of copy. Bottom 20%: [YOUR PRODUCT] centered or slightly right, product-only on white, clean studio shot angle. No icons, no badges, no CTA button. The writing IS the ad. 1:1 aspect ratio.`,
  },
  {
    id: 24,
    name: "Product + Comment Callout (Faux Social Proof)",
    namebn: "প্রোডাক্ট + কমেন্ট কলআউট (ফো সোশ্যাল প্রুফ)",
    description: "Organic-looking Facebook comment screenshot below a clean product shot.",
    descriptionbn: "ক্লিন প্রোডাক্ট শটের নিচে অর্গানিক ফেসবুক কমেন্ট স্ক্রিনশট।",
    categories: ["Social Proof", "UGC"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design and packaging precisely. Create: a social proof ad. Top 55%: [YOUR PRODUCT] centered on a clean white background, studio-lit, shot at 85mm f/2.8 with soft shadow. Product cap/lid slightly open or [DETAIL showing use]. A few [LOOSE UNITS like gummies / capsules] spilling casually at the base. Bottom 45%: a realistic Facebook-style comment card. Left: small circular profile photo of [PERSON DESCRIPTION like a man in his 30s, friendly smile, casual]. Bold name "[FIRST NAME + LAST INITIAL like Alan R.]" above the comment. Comment text in regular weight: "[TESTIMONIAL 2-3 sentences touching on a specific problem and the product being a game-changer]". Below comment: "[TIMEFRAME like 4w]" · Like · Reply in gray. Bottom right of comment: Facebook-style reaction emojis (thumbs up + heart) with "[COUNT like 33]". Should look like an organic screenshot, not designed. 1:1 aspect ratio.`,
  },
  {
    id: 25,
    name: "Us vs. Them Color Split",
    namebn: "আমরা বনাম তারা কালার স্প্লিট",
    description: "Vibrant color split comparison with bold benefit/weakness stacks.",
    descriptionbn: "ভাইব্র্যান্ট কালার স্প্লিট তুলনা।",
    categories: ["Comparison"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design and colors precisely. Create: a side-by-side comparison ad divided vertically into two equal halves. Left half: [PRIMARY BRAND COLOR like vibrant teal] background. [YOUR PRODUCT] photographed with dynamic energy — [ACTION DETAIL like chocolate dripping / liquid pouring] to convey indulgence. Brand logo in bold white upper-left. Below product: vertical stack of 4 benefits, each with a green circle checkmark emoji: "[STRENGTH 1-4 like ≤2G SUGAR / ALL NATURAL INGREDIENTS / ≥6G FIBRE / 12G PROTEIN]" in bold white uppercase. Right half: [CONTRAST COLOR like pale cream/beige] background. Generic unbranded competitor product [DESCRIPTION like crumpled foil-wrapped chocolate bar]. Header: "[COMPETITOR CATEGORY like Other chocolate bars]" in dark text. Below: vertical stack of 4 weaknesses, each with a red circle X emoji: "[WEAKNESS 1-4 like 29G SUGAR / FULL OF FRUCTOSE CORN SYRUP / 1G FIBRE / 2G PROTEIN]" in bold dark uppercase. Center divider: a comic-style "VS" burst graphic in [ACCENT COLOR like coral/red]. 1:1 aspect ratio.`,
  },
  {
    id: 26,
    name: "Stat Callout (Data-Driven Lifestyle)",
    namebn: "স্ট্যাট কলআউট (ডেটা-ড্রিভেন লাইফস্টাইল)",
    description: "Lifestyle photo top. Dark gradient stat headline bottom.",
    descriptionbn: "উপরে লাইফস্টাইল ফটো। নিচে ডার্ক গ্র্যাডিয়েন্ট স্ট্যাট হেডলাইন।",
    categories: ["Stats"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Match exact brand colors and typography. Create: a statistic-led ad. Top 50%: lifestyle product photography — [SCENE like a woman's hands holding the product pad / person using the product in context] on a [MOOD like warm, skin-toned, soft-focus] background. Product packaging visible in frame. Middle: brand logo centered with thin horizontal rules on either side as a visual divider. Bottom 50%: dark gradient overlay (fading from transparent to [DARK COLOR like deep brown/black]). Large bold uppercase sans-serif text: "[STAT-DRIVEN HEADLINE with specific percentages like AFTER SWITCHING TO [BRAND], [X]% OF USERS [RESULT], WHILE [Y]% [SECOND RESULT]]." Key result phrases highlighted in [ACCENT COLOR like soft pink / brand secondary color]. The statistic IS the headline — no separate subhead needed. 4:5 aspect ratio.`,
  },
  {
    id: 27,
    name: "Benefit Checklist Showcase (Split Product + Info)",
    namebn: "বেনিফিট চেকলিস্ট শোকেস",
    description: "Split product + info. Information-dense but scannable.",
    descriptionbn: "স্প্লিট প্রোডাক্ট + ইনফো। ইনফরমেশন-ডেন্স কিন্তু স্ক্যানযোগ্য।",
    categories: ["Product Hero"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design and brand colors precisely. Create: an information-dense benefit ad, split composition. Left 45%: overhead product shot — [PRODUCT DISPLAY DESCRIPTION like a white bowl filled with fresh dog food divided into labeled sections by thin white lines, each section labeled in curved white text: "[VARIETY 1-4 like CHICKEN & YAMS / BEEF N' RICE / SALMON N' RICE / TURKEY & YAMS]"]. Shot on 50mm f/4, clean white surface. Right 55%: white background. Top: [STAR RATING like five gold stars] with "[REVIEW COUNT like 10,000+ REVIEWS]" in [BRAND COLOR]. Brand logo. Below: [BRAND COLOR] serif or sans-serif headline: "[HEADLINE like Made for the pickiest dogs]". Then 3 checkmark benefit rows, each with a filled [BRAND COLOR] circle checkmark + bold text: "[BENEFIT 1-3 like Head turning aroma / No additives, flavors, or preservatives / Ready to serve from the pouch]". Bottom right: large rounded [ACCENT COLOR] CTA button reading "[CTA like SHOP NOW]". 1:1 aspect ratio.`,
  },
  {
    id: 28,
    name: "Feature Arrow Callout / Product Annotation",
    namebn: "ফিচার অ্যারো কলআউট / প্রোডাক্ট অ্যানোটেশন",
    description: "Product held in hand. Four editorial arrows point to benefit callouts.",
    descriptionbn: "হাতে ধরা প্রোডাক্ট। চারটি এডিটোরিয়াল অ্যারো বেনিফিট কলআউটে পয়েন্ট করে।",
    categories: ["Product Hero"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match exact brand colors and typography style. Create: a product annotation ad on a [BACKGROUND like warm cream/light yellow textured] background. Top: italic serif headline "[BENEFIT STATEMENT like Barista grade coffee. Instant. Affordable.]" in [BRAND COLOR like dark navy]. Below in massive bold sans-serif: "[VALUE PROP like ALL IN ONE]". Center: [PERSON'S HAND] holding [YOUR PRODUCT] at a natural angle. Four curved arrows in [BRAND COLOR] pointing from the product outward to four benefit callout labels arranged around it in bold [BRAND COLOR] text: "[CALLOUT 1-4 like NO sugar or calories / Multiple Flavors / Iced, cold or hot / Smooth and delicious]". Arrows should feel hand-drawn or editorial, not rigid. Bottom: full-width [CONTRAST COLOR like deep navy] banner with [PROMO TEXT like HUGE SALE + FREE GIFTS] in bold [ACCENT COLOR like gold/white] with optional emoji accents. 1:1 aspect ratio.`,
  },
  {
    id: 29,
    name: "UGC + Viral Post Overlay",
    namebn: "UGC + ভাইরাল পোস্ট ওভারলে",
    description: "Casual selfie. Overlaid Reddit/X opinion post. The hook is the opinion.",
    descriptionbn: "ক্যাজুয়াল সেলফি। উপরে Reddit/X মতামত পোস্ট। হুকটাই মতামত।",
    categories: ["UGC"],
    aspectRatio: "9:16",
    prompt: `Use the attached images as brand reference for product color ONLY. Do NOT use ad layouts or polish. This should look completely native and organic. Create: a casual selfie of [PERSON like a man in mid-20s, beanie, crewneck sweatshirt] doing something mundane [ACTION like brushing teeth, making coffee, cooking]. iPhone front camera, slightly grainy, bathroom/kitchen lighting, no professional setup. Overlaid in the center of the frame: a realistic screenshot of a [PLATFORM like Reddit / Twitter / X] post. [POST DETAILS like subreddit name, username, timestamp, upvote count]. Post title in bold: "[PROVOCATIVE OPINION HEADLINE related to the product's problem/benefit space]". Post body in regular text: "[2-3 sentences expanding on the opinion]". The post should feel like the person is reacting to it or sharing it — NOT selling a product. No product visible. No brand logo. No CTA. The hook is the opinion. 9:16 aspect ratio.`,
  },
  {
    id: 30,
    name: "Hero Statement + Icon Benefit Bar",
    namebn: "হিরো স্টেটমেন্ট + আইকন বেনিফিট বার",
    description: "Power statement top. Lifestyle photo center. Three icon benefits bottom.",
    descriptionbn: "উপরে পাওয়ার স্টেটমেন্ট। মাঝে লাইফস্টাইল ফটো। নিচে তিনটি আইকন বেনিফিট।",
    categories: ["Product Hero"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match exact brand colors, packaging, and typography. Create: a bold statement ad. Top 15%: white banner overlay with massive bold [BRAND COLOR like dark purple] uppercase sans-serif headline: "[2-3 WORD POWER STATEMENT like APPETITE KILLER.]" with a period for punch. Middle 55%: lifestyle product photo — [SCENE like woman's hand holding a capsule above an open supplement jar on a clean surface, soft natural light]. Product label and branding clearly visible. Bottom 25%: [SOFT BRAND COLOR like lavender/light purple] background. Three evenly spaced icon-and-text benefit columns: [ICON 1 + LABEL like (crossed-out burger icon) CURB APPETITE] | [ICON 2 + LABEL like (lightning bolt icon) BURN CALORIES] | [ICON 3 + LABEL like (heart + body icon) LOSE WEIGHT]. Icons are simple line-drawn in [BRAND COLOR] circles. Very bottom edge: scrolling ticker bar in [DARK BRAND COLOR] with repeating text: "[SOCIAL PROOF like OVER 300K+ LIVES CHANGED]". 1:1 aspect ratio.`,
  },
  {
    id: 31,
    name: "Comparison Grid / Table",
    namebn: "কম্পারিজন গ্রিড / টেবিল",
    description: "Structured comparison grid. The copy contrast does the work. Meme-viral format.",
    descriptionbn: "স্ট্রাকচার্ড কম্পারিজন গ্রিড। কপি কনট্রাস্টই কাজ করে। মিম-ভাইরাল ফরম্যাট।",
    categories: ["Comparison"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product packaging precisely. Create: a structured comparison grid ad on white background. Top row divided 50/50: Left: [YOUR PRODUCT] packaging photographed clean on white with [DETAIL like chips spilling out]. Right: [COMPETITOR PRODUCT] packaging on white. Below: three horizontal rows spanning full width, each divided 50/50 by a thin black vertical line and separated by thin black horizontal lines. Each row compares one attribute: Row 1: "[YOUR ADVANTAGE like Uses beef tallow.]" vs "[COMPETITOR WEAKNESS like Uses seed oils.]". Row 2: "[YOUR ADVANTAGE like Organic corn.]" vs "[COMPETITOR WEAKNESS like Pesticide corn.]". Row 3: "[YOUR ADVANTAGE like Tastes amazing.]" vs "[COMPETITOR WEAKNESS like Doesn't even taste good.]" All text in bold black serif or heavy sans-serif, centered in each cell. No icons, no colors, no checkmarks — the copy contrast does the work. Should feel like a meme-format comparison that would go viral on X or Reddit. 1:1 aspect ratio.`,
  },
  {
    id: 32,
    name: "UGC Story Callout / Text Bubble Explainer",
    namebn: "UGC স্টোরি কলআউট / টেক্সট বাবল এক্সপ্লেইনার",
    description: "Real Instagram Story feel. Five text bubbles educate and convert.",
    descriptionbn: "রিয়েল ইনস্টাগ্রাম স্টোরি ফিল। পাঁচটি টেক্সট বাবল এডুকেট ও কনভার্ট করে।",
    categories: ["UGC"],
    aspectRatio: "9:16",
    prompt: `Use the attached images as brand reference for product color and packaging ONLY. Do NOT use ad layouts or polish. This must look like a real person's Instagram Story. Create: a casual iPhone photo of [PERSON DESCRIPTION like a woman's hand with clean natural nails] holding [YOUR PRODUCT with key packaging details] at a slight angle over [SURFACE/SETTING like a clean white desk with lifestyle props]. Natural overhead daylight, slightly warm, iPhone 15 quality. Scattered across the frame: 5 text bubbles using Instagram Story's built-in highlighted text tool. Each bubble must have a highlighted background for readability, with varied highlight colors between bubbles. Bubble 1: "[TOPIC + EMOJI like gut health 🌱]" large and bold. Bubble 2: "[EDUCATIONAL HOOK — a surprising stat or mechanism about why this category matters]". Bubble 3: "[WHY THIS PRODUCT — the specific feature that makes it different, excited informal tone]". Bubble 4: "[PERSONAL RESULT — early experience update, first-person, with emoji]". Bubble 5: "[BRAND ENDORSEMENT — one short line of approval]". Should feel casual and hand-placed, not designed. 9:16 aspect ratio.`,
  },
  {
    id: 33,
    name: "Faux Press / News Articles Screenshot",
    namebn: "ফো প্রেস / নিউজ আর্টিকেল স্ক্রিনশট",
    description: "Looks like a real online news article someone screenshotted.",
    descriptionbn: "রিয়েল অনলাইন নিউজ আর্টিকেলের মতো দেখায়।",
    categories: ["Editorial", "Social Proof"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Create: a static ad designed to look like a real online news article screenshot. Top 25%: white background with a realistic major publication masthead/logo in large bold black serif text [PUBLICATION STYLE like "Daily Mail" or "TODAY" or "INSIDER"]. Below: thin gray horizontal rule. Small gray text "Latest Headlines" left-aligned. Then: bold black serif headline spanning full width: "[HEADLINE like 'It's my holy grail product': The $[PRICE] [PRODUCT CATEGORY] with over [NUMBER] five-star reviews]". Bottom 60%: two side-by-side casual UGC-style photos of [PEOPLE like two different young women, one brunette, one blonde] each holding [YOUR PRODUCT] in a casual selfie pose — one taken in natural daylight, one in warm indoor evening light. Photos should look like real customer submissions, not studio shots. No brand logo. No CTA. Should look like an organic article screenshot someone would share to their story. 4:5 aspect ratio.`,
  },
  {
    id: 34,
    name: "Faux iPhone Notes / App Screenshot",
    namebn: "ফো আইফোন নোটস / অ্যাপ স্ক্রিনশট",
    description: "Disguised as an iOS Notes screenshot. Product breaks the frame.",
    descriptionbn: "iOS নোটস স্ক্রিনশট হিসেবে ছদ্মবেশ। প্রোডাক্ট ফ্রেম ভাঙে।",
    categories: ["UGC"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design and packaging precisely. Create: a static ad disguised as an iPhone Notes app screenshot. Top: realistic iOS status bar (time "[TIME like 10:45]", signal bars, wifi icon, battery icon). Below: iOS Notes navigation — blue "< All iCloud" back arrow left, share icon and three-dot menu icon right. Below nav: small gray timestamp text "[DATE like 13 July 2023 10:44]". Main content area on white background: bold black serif headline "[HEADLINE like In Just [DOSAGE] A Day]". Below: [3 BENEFIT ROWS], each with a [BRAND COLOR] filled circle checkmark + [EMOJI] + bold black text using food-equivalency format: "[BENEFIT 1 like More Vitamin D than 800 mushrooms]" / "[BENEFIT 2 like More Folate than 4 cups of spinach]" / "[BENEFIT 3 like More Vitamin B1 than 7 cups of broccoli]". Right side, overlapping the benefit text slightly: [YOUR PRODUCT] at a slight angle with [DETAILS like a few gummies/capsules spilling out at the base]. Product should feel casually placed into the note layout, breaking the frame slightly. Clean white background throughout. 1:1 aspect ratio.`,
  },
  {
    id: 35,
    name: "Hero Product Showcase + Stat Bar",
    namebn: "হিরো প্রোডাক্ট শোকেস + স্ট্যাট বার",
    description: "Superlative claim top. Hero-lit product center. Three-metric stat bar bottom.",
    descriptionbn: "উপরে সুপারলেটিভ ক্লেইম। মাঝে হিরো-লিট প্রোডাক্ট। নিচে থ্রি-মেট্রিক স্ট্যাট বার।",
    categories: ["Product Hero", "Stats"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design, wrapper, and brand colors precisely. Create: a product showcase ad on a [BACKGROUND COLOR like warm sand/beige/cream] background. Top: large bold [BRAND COLOR like chocolate brown] uppercase sans-serif headline: "[SUPERLATIVE CLAIM like THE WORLD'S HEALTHIEST CHOCOLATE]". Below headline: white rounded-rectangle CTA button with [BRAND COLOR] uppercase text "[CTA like EXPLORE NOW]". Center: [YOUR PRODUCT] in full packaging, angled slightly, hero-lit with soft studio lighting. Surrounding the product: [SCATTERED ELEMENTS like broken chocolate pieces, cocoa powder dust, crumbs, ingredient pieces] arranged in an exploded/radial pattern creating visual energy and texture on the background surface. Bottom: a white or light rounded-pill stat bar spanning the width with three metrics separated by thin vertical lines: "[STAT 1 like 12G OF PROTEIN]" | "[STAT 2 like ≤2G OF SUGAR]" | "[STAT 3 like ≤3G OF NET CARBS]" in bold [BRAND COLOR] text. Numbers should be large and dominant, labels smaller below. 1:1 aspect ratio.`,
  },
  {
    id: 36,
    name: "Whiteboard Before / After + Product Hold",
    namebn: "হোয়াইটবোর্ড আগে / পরে + প্রোডাক্ট হোল্ড",
    description: "Hand-drawn whiteboard illustration. Real-life setting. Looks like someone's tip.",
    descriptionbn: "হাতে আঁকা হোয়াইটবোর্ড ইলাস্ট্রেশন। বাস্তব সেটিং। কারো টিপসের মতো দেখায়।",
    categories: ["Before & After", "UGC"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference for product packaging ONLY. Do NOT use ad layouts or polish. This should look like a real person's photo. Create: a lifestyle photo set in [SETTING like a bright modern kitchen]. In the background: a small tabletop dry-erase whiteboard or flip-chart propped up on [SURFACE like a marble countertop]. On the whiteboard: two simple hand-drawn black marker line illustrations side by side — left drawing labeled "[BEFORE LABEL like De esto...]" showing [BEFORE STATE like a bloated midsection outline with dots/texture], an arrow pointing right to a second drawing labeled "[AFTER LABEL like A esto!]" showing [AFTER STATE like a flatter, smoother midsection outline]. Below the drawings on the whiteboard: handwritten text in black marker "[HANDWRITTEN CTA like If you want progress during [PROBLEM], you need this!]". In the foreground: [PERSON'S HAND] holding [YOUR PRODUCT] up next to the whiteboard, positioned in the lower-right of the frame. Product label clearly visible. Shot on iPhone, natural kitchen lighting, casual and educational. 4:5 aspect ratio.`,
  },
  {
    id: 37,
    name: "Hero Statement + Icon Bar + Offer Burst (Promo Variant)",
    namebn: "হিরো স্টেটমেন্ট + আইকন বার + অফার বার্স্ট (প্রমো ভ্যারিয়েন্ট)",
    description: "Promotional variant of the hero statement. Moody background. Discount starburst.",
    descriptionbn: "হিরো স্টেটমেন্টের প্রমো ভ্যারিয়েন্ট। মুডি ব্যাকগ্রাউন্ড। ডিসকাউন্ট স্টারবার্স্ট।",
    categories: ["Offer", "Product Hero"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference. Match the exact product design and brand colors precisely. Create: a promotional variant of a hero statement ad on a [BACKGROUND like dark charcoal/moody gray] background. Top 12%: white or light banner with massive bold [DARK COLOR] uppercase sans-serif headline: "[PROVOCATIVE 2-3 WORD STATEMENT like FUPA KILLER.]" with a period for punch. Upper-left of product area: a [BRIGHT ACCENT COLOR like neon green/lime] comic-style starburst badge rotated slightly, reading "GET UP TO [DISCOUNT like 40%] OFF" in bold black text. Center: [PERSON'S HAND] gripping [YOUR PRODUCT] from above, lifting it off its [PACKAGING like retail box] below. Product label and branding clearly visible. Moody, slightly dramatic lighting. Bottom 20%: three evenly spaced icon-and-text benefit columns on a semi-transparent dark strip: [ICON 1 + LABEL like (crossed-out burger) CURB APPETITE] | [ICON 2 + LABEL like (lightning bolt) BURN CALORIES] | [ICON 3 + LABEL like (heart + body) LOSE WEIGHT]. Icons in simple line-art circles with [ACCENT COLOR] highlights. Very bottom: full-width [BRIGHT ACCENT COLOR] banner with bold [DARK] text: "[PROMO like BLACK FRIDAY SPECIAL]". 1:1 aspect ratio.`,
  },
  {
    id: 38,
    name: "UGC Lifestyle + Product + Review Card (Split)",
    namebn: "UGC লাইফস্টাইল + প্রোডাক্ট + রিভিউ কার্ড (স্প্লিট)",
    description: "Vertical split. Casual lifestyle left. Branded product + review card right.",
    descriptionbn: "ভার্টিকাল স্প্লিট। বাম দিকে ক্যাজুয়াল লাইফস্টাইল। ডান দিকে ব্র্যান্ডেড প্রোডাক্ট + রিভিউ কার্ড।",
    categories: ["Testimonial", "UGC"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Match the exact product design and brand colors precisely. Create: a vertical split social proof ad. Left 55%: a casual UGC-style photo of [PERSON like a blonde woman in her early 30s, wearing a casual zip-up sweater] enjoying the product in context — [ACTION like sipping an iced drink through a gold metal straw in a bright café setting]. Natural lighting, warm and inviting, iPhone-quality casual feel. The person should look genuinely happy, not posed. Right 45%: solid [PRIMARY BRAND COLOR like deep indigo/purple] background. Top-right: small decorative sparkle/star accents in [ACCENT COLOR like gold/yellow]. Floating center-right: [YOUR PRODUCT] at a slight angle, studio-lit on the colored background. Below product: a white rounded-rectangle review card with: five filled [ACCENT COLOR] stars at top, then italic or casual serif text: "[SHORT REVIEW QUOTE like "I will never get drive-thru coffee again"]" in [BRAND COLOR]. Bottom center: [BRAND LOGO] in white on the colored background, with small decorative sparkle accents. 4:5 aspect ratio.`,
  },
  {
    id: 39,
    name: "Curiosity Gap + Scroll-Stopper Hook",
    namebn: "কিউরিওসিটি গ্যাপ + স্ক্রোল-স্টপার হুক",
    description: "No product. No logo. Just a truncated caption and a problem visual.",
    descriptionbn: "কোনো প্রোডাক্ট নেই। কোনো লোগো নেই। শুধু ট্রান্কেটেড ক্যাপশন ও সমস্যার ভিজ্যুয়াল।",
    categories: ["UGC"],
    aspectRatio: "1:1",
    prompt: `Use the attached images as brand reference for visual tone ONLY. Do NOT include any product, logo, or branding. Create: a scroll-stopping curiosity ad designed to look like a truncated social media post. Top 35%: clean white background with large bold black sans-serif text (heavy weight, tight leading): "[HOOK HEADLINE like Most [AUDIENCE] don't realize THIS is why [PROBLEM STATEMENT] but did you know...]". The last few words should be followed by "...more" in lighter gray text, mimicking a truncated Facebook/Instagram caption that requires clicking "more" to expand. Bottom 65%: a close-up, slightly uncomfortable or attention-grabbing photo of [PROBLEM VISUAL like the specific physical symptom or problem the product solves — shown on the subject, no product visible]. Photo should feel real and editorial, not stock. Slightly shallow depth of field. No text on the photo. No product. No logo. No CTA. The entire purpose is to provoke curiosity and earn the click. 1:1 aspect ratio.`,
  },
  {
    id: 40,
    name: "Native / Ugly Post-It Note Style (Product Hero)",
    namebn: "নেটিভ / আগলি পোস্ট-ইট নোট (প্রোডাক্ট হিরো)",
    description: "Real-life product photo. Handwritten post-it stuck on the packaging. Brutally organic.",
    descriptionbn: "বাস্তব জীবনের প্রোডাক্ট ফটো। প্যাকেজিংয়ে হাতে লেখা পোস্ট-ইট। নিখাদ অর্গানিক।",
    categories: ["UGC", "Product Hero"],
    aspectRatio: "4:5",
    prompt: `Use the attached images as brand reference. Match the exact [PRODUCT DESCRIPTION — shape, color, label details, key typography on packaging] precisely. Create: a lifestyle product photo set in [REAL-LIFE SETTING — e.g. warm kitchen floor / bathroom counter / living room coffee table] with [LIGHTING DESCRIPTION — e.g. soft natural daylight from a nearby window / warm diffused morning light] and a naturally blurred background showing [BACKGROUND DETAILS — e.g. lower kitchen cabinets and a dog bowl / mirror edge and steam / couch cushions]. Frame is very slightly off-center — product not perfectly centered, [LEFT / BOTTOM / RIGHT] edge of product very slightly cropped — feels found rather than composed. Slight natural sensor grain consistent with a phone camera in indoor daylight. Subtle natural vignette at frame corners. Center of frame, large and dominant: [FULL PRODUCT DESCRIPTION — packaging colors, key label text, distinguishing visual features] sitting on [SURFACE — e.g. light wood floor / raw wood shelf / marble counter], slightly angled toward the viewer. [SCATTERED SURFACE DETAIL — e.g. a few scattered kibble pieces / sea salt crystals / product crumbs] on the surface around the base of the product for casual realism. Stuck directly onto the front face of the product: a [POST-IT COLOR — yellow default] square post-it note, slightly crooked and not perfectly straight — slightly trapezoid from the angle it was pressed on. Realistic paper texture with a horizontal crease across the middle as if it was folded once. Subtle curl at bottom-right corner only. Held at the top by a small piece of [TAPE COLOR — clear / yellow / white] tape, slightly wrinkled — not a self-adhesive strip. One word in the handwriting is slightly heavier-inked or underlined from natural pen pressure. Handwritten in thick black marker-style lettering, imperfect and uneven, lowercase natural writing — not formatted, not centered, not evenly spaced: "[LINE 1 — lowercase, short, setup or hook]" line break "[LINE 2 — continuation or turn]" line break "[LINE 3 — punchline, result, or kicker]" line break "[LINE 4 — optional final beat or emoji]" No attribution line. No signature. Bottom center of frame, outside the photo on a plain white or off-white strip: small plain lowercase sans-serif caption text, looks like someone typed it under an organic post: "[brand url] — [3-5 word casual caption, sounds typed not written]" No logo overlay anywhere in the frame. Brand identity carried entirely by the product packaging visible in the photo. No border. [MOOD — 3 adjectives]. 4:5 aspect ratio.`,
  },
]

// ─────────────────────────────────────
// BANGLISH INSTRUCTION (appended when BN language is selected)

export const BANGLISH_INSTRUCTION = `All text overlays, headlines, CTAs, and copy within the image should be written in Banglish (Bengali written in English script, conversational Dhaka tone). Avoid formal Bengali. Match the emotional register of Bangladeshi Facebook and Instagram ad copy.`

// ─────────────────────────────────────
// SHOP DNA VARIABLE SUBSTITUTION

export function fillTemplatePrompt(prompt: string, workspace: any): string {
  const brandColors = Array.isArray(workspace?.brand_colors)
    ? workspace.brand_colors.map((c: any) => c?.hex || c).filter(Boolean)
    : []
  const brandFonts = workspace?.brand_fonts || {}

  const replacements: Record<string, string> = {
    '[BRAND]': workspace?.shop_name || '[BRAND]',
    '[BRAND NAME]': workspace?.shop_name || '[BRAND NAME]',
    '[YOUR BRAND]': workspace?.shop_name || '[YOUR BRAND]',
    '[PRIMARY BRAND COLOR]': brandColors[0] || '[PRIMARY BRAND COLOR]',
    '[BRAND COLOR]': brandColors[0] || '[BRAND COLOR]',
    '[SECONDARY COLOR]': brandColors[1] || '[SECONDARY COLOR]',
    '[CONTRAST COLOR]': brandColors[1] || '[CONTRAST COLOR]',
    '[ACCENT COLOR]': brandColors[2] || '[ACCENT COLOR]',
    '[PRIMARY FONT]': brandFonts?.heading || '[PRIMARY FONT]',
    '[SECONDARY FONT]': brandFonts?.body || '[SECONDARY FONT]',
    '[YOUR PRODUCT]': workspace?.key_products || '[YOUR PRODUCT]',
    '[SPECIFIC PRODUCT]': workspace?.key_products || '[SPECIFIC PRODUCT]',
    '[PHOTOGRAPHY STYLE]': workspace?.brand_tone || '[PHOTOGRAPHY STYLE]',
    '[MOOD]': workspace?.brand_tone || '[MOOD]',
    '[TARGET AUDIENCE]': workspace?.target_audience || '[TARGET AUDIENCE]',
    '[WEBSITE]': workspace?.shop_url || '[WEBSITE]',
  }

  let filled = prompt
  for (const [key, value] of Object.entries(replacements)) {
    filled = filled.replaceAll(key, value)
  }
  return filled
}
